#164047064 Build out REST Endpoints for Articles (CRUD)
andela/ah-olympians pull request #18
Opened 2019-03-13 08:15 UTC by winniekariuki

#### What does this PR do?
This pr creates,retrieves,updates and delete articles.
#### Description of Task to be completed?
Have the following working endpoints:
```GET  /api/articles/<slug>/```
```GET /api/articles/```
```POST /api/articles/```
```PUT /api/articles/<slug>/```
```DELETE /api/articles/<slug>/```
#### How should this be manually tested?
After cloning this repo,cd into it and run ```python manage.py runserver``` and test all the above endpoints using postman.
#### What are the relevant pivotal tracker stories?
#164047064

2019-03-13 12:52 UTC, JumaKahiga commented
Kindly adjust views to APIView or Generics for consistency with the existing codebase.

2019-03-13 18:19 UTC, JoanNgatia requested changes

2019-03-13 18:19 UTC, JoanNgatia commented on .travis.yml
> +addons:
We should only need the one `addons` value here

2019-03-13 18:19 UTC, JoanNgatia commented on .env.example
> +
You'll need to remove the duplicates from this file

2019-03-14 06:22 UTC, kelvinndmo commented on .travis.yml
> +addons:
@JoanNgatia sometimes we got an error on Travis which was as a result of Travis building with postgres 9.2 which is no longer supported.To solve this you have to specify the postgres version and that is what addons does.

2019-03-14 12:49 UTC, JoanNgatia approved these changes

2019-03-14 12:49 UTC, merged