#164047076 add read time for an article
andela/ah-olympians pull request #27
Opened 2019-03-21 07:25 UTC by Kibetchirchir

#### Description
___
When a user publishes an article he/she can see the approximate readtime  

#### Type of Change
___

- [x] New Feature

#### How has this been tested
___
- [x] Unit tests
 - [x]  End to end testing

#### Checklist
___
- [x] Tests are included to show/proof the feature works.

#### Pivotal Tracker
___
[164047076](https://www.pivotaltracker.com/story/show/164047076)

2019-03-21 12:02 UTC, JumaKahiga commented
Great execution.

2019-03-21 18:49 UTC, kevpy commented on authors/apps/article/serializers.py
> +import readtime
Let local imports come after 3rd party libraries. 
`import readtime` should come before any other local imports

2019-03-21 18:53 UTC, JoanNgatia requested changes
@Kibetchirchir Make the change on the order of imports and we'll be good to go on this PR

2019-03-22 05:49 UTC, Kibetchirchir commented on authors/apps/article/serializers.py
> +import readtime
@kevpy thanks I have resolved as advised

2019-03-22 07:17 UTC, JoanNgatia requested changes

2019-03-22 07:17 UTC, JoanNgatia commented on authors/apps/article/serializers.py
> +import readtime
@Kibetchirchir  order of these imports should be readtime, django, rest_framework and then imports from local files.

2019-03-22 07:28 UTC, JoanNgatia approved these changes

2019-03-22 07:28 UTC, merged