#164047071 Users should receive notifications
andela/ah-olympians pull request #30
Opened 2019-03-22 08:26 UTC by JumaKahiga

#### Description
___
With users having the ability to follow each other and favorite articles, user experience can be increased by allowing users to get notifications when an author they follow publishes or an article they favorite receives a comment. 

#### Type of Change
___
[x] New Feature

#### How has this been tested
___
[x] Unit tests

#### Checklist
___
[x] I have added tests that prove my feature is working

#### Pivotal Tracker
___
[164047071](https://www.pivotaltracker.com/story/show/164047071)

2019-03-24 16:51 UTC, mnswaleh commented on authors/apps/article/views.py
> +        try:
You could reuse
`
        CommentVerification.check_profile(self, request.user.id)
`
to verify if profile exists

2019-03-24 17:06 UTC, JumaKahiga commented on authors/apps/article/views.py
> +        try:
Thank you for that heads-up @mnswaleh

2019-03-25 06:14 UTC, winniekariuki reviewed
Nice implementation of the feature but perhaps you can make your docstrings more descriptive in future to aid a reader to understand your code.

2019-03-25 07:34 UTC, JoanNgatia requested changes

2019-03-25 07:34 UTC, JoanNgatia commented on authors/apps/article/views.py
> +                for return_data in serial_datsa['subcomments']:
Nitpick fix: typo `serial_datsa`

2019-03-27 07:37 UTC, JoanNgatia requested changes

2019-03-27 07:37 UTC, JoanNgatia commented on authors/apps/article/tests/test_report_article.py
> +        print(create_profile, ">>>>>>>>>")
You should remove the print statement.

2019-03-27 07:37 UTC, JoanNgatia commented on authors/apps/article/tests/test_article.py
> +    def test_delete_unexisting_article(self):
rename this to non-existent

2019-03-27 07:37 UTC, JoanNgatia commented on authors/apps/profiles/serializers.py
> +	"""Serializes following/followers list."""
This comment isn't needed as the class name is self-explanatory, in my opinion.

2019-03-27 07:37 UTC, JoanNgatia commented on authors/apps/profiles/serializers.py
> +	"""Serializes notifications list."""
Edit this comment to differentiate it from the `NotifySerializer`. You can add a comment why the notify serializer had to be different. i.e it's use case

2019-03-28 09:53 UTC, JoanNgatia approved these changes

2019-03-28 09:53 UTC, merged