fix(settings): Add CROS- origin
andela/ah-olympians pull request #34
Opened 2019-03-30 11:01 UTC by Kibetchirchir

#### Description
___
A user can be able to consume the API without getting CROS origin error

#### Type of Change
___

- [x] New Feature

#### How has this been tested
___
- [x] Unit tests
 - [x]  End to end testing

#### Checklist
___
- [x] Tests are included to show/proof the feature works.

#### Pivotal Tracker
___
[164047056](https://www.pivotaltracker.com/story/show/164047056)

2019-04-01 07:40 UTC, JumaKahiga commented
Thanks for working on this issue Chirchir.

2019-04-02 09:19 UTC, JoanNgatia requested changes

2019-04-02 09:19 UTC, JoanNgatia commented on requirements.txt
> +mypy==0.670
Do we need the libraries `mypy`, `mypy-extensions`, `typed-ast` and `typing-extensions` for this feature fix?

2019-04-02 12:50 UTC, JoanNgatia approved these changes

2019-04-02 12:50 UTC, merged